### ISSUE TITLE
Implement correct gnome ball item behaviour

### ISSUE THREAD

**Issue by Kenix3** [Open-RSC/Game#114]
----------------------
 Gnome Ball
----------------------

- What happens when the recipient has a full inventory?
- What happens when the recipient has the bank open?
- What happens when the recipient has a shop open?
- What happens when the recipient is dueling/staking?
- What happens when the recipient is in combat?
- What happens when the recipient has a dialogue menu is open?
- What happens when the recipient is in the middle of an action? (Ex. mining, fishing, woodcut, firemaking)
- What happens when the recipient already has a gnome ball?
- What happens if you pull more than one out at a time from the bank?
- Is there any message when attempting to pick up a gnome ball while already holding one?

**Comment by kInGkRiStOf** [comment]
- What happens when the recipient has a full inventory? drops under them
- What happens when the recipient has the bank open? goes into inventory, and shows up in bank, unless full inv, then drops under them
- What happens when the recipient is dueling/staking? goes into inv
-when you have space in inventory, and are in the bank screen, it goes into your inventory, viewable in bank.
-when you are full inventory, it drops to ground under you instead.
-okay. gnome ball will interupt the store screen, and take you out of the store. it will also show the "__ is shooting at you", and it will go into your inventory
![gnomeball banking](https://user-images.githubusercontent.com/36169371/43344095-e0f3e93c-91e8-11e8-823b-55191295effc.png)
![gnomeball banking space](https://user-images.githubusercontent.com/36169371/43344096-e10d8edc-91e8-11e8-8477-243dfc9a9723.png)

**Comment by kInGkRiStOf** [comment]
[Gnomeball + smuggle.zip](https://github.com/Open-RSC/Game/files/2257813/Gnomeball.%2B.smuggle.zip)
my replay

**Comment by Kenix3** [comment]
Reopened to be retested and examined in v2

**Comment by lmsv-mx123** [comment]
Placed the fix with the minigame update
