### ISSUE TITLE
dual logging causes first player to glitch until server restart

### ISSUE THREAD

**Issue by Marwolf** [Open-RSC/Game#116]
Cannot login or use player. He blinks in and out of existence to other players in game.

**Comment by Marwolf** [comment]
May or may not kick/freeze client of first player. Second player is unaffected.

**Comment by Marwolf** [comment]
Affected player login returns client error "Player account in use"

**Comment by Marwolf** [comment]
Attempts to kick the player do not affect it.

**Comment by Marwolf** [comment]
This issue is linked to #115

**Comment by Kenix3** [comment]
Caused by the EntityList container created as part of getPlayersByIp clashing with the World.players container via the way of added Entity.getIndex()

Unknown why the original server code added a custom container. Only thought can be in order to reference something via an index, but classic Java contains have an indexOf() method. Regardless, fix was to use a classic java container for the return of World.getPlayersByIp()

In the future, look into converting usages of EntityList into classic java ArrayList.

**Comment by Marwolf** [comment]
Fixed in f5b23db939e892101246cbd413c016b0f302bce8
