### ISSUE TITLE
Smithing menu doesn't reset when cancelled out of

### ISSUE THREAD

**Issue by Hubcapp** [Open-RSC/Game#1321]
**Describe the bug**
If you start smithing something, click into the smithing menu at least once, then click out, then use bar on anvil again, the menu becomes broken until you smith something.

**To Reproduce**
start smithing on anvil -> click an option -> cancel out -> click another option -> ??? (remembers where you were in the menu last time and doesn't cancel menu progress, only visually)

Happened to me when using bronze bar on doric's anvil -- possible it doesn't happen with other tiers of bar or with other anvils -- haven't looked into it.

**Expected behavior**
Menu needs to reset when cancelled out of.

**Comment by kInGkRiStOf** [comment]
Not fixed.
https://gyazo.com/a17ab6c68e3b630a227cad4373beee64

**Comment by Christofosho** [comment]
This happens because the showMenu function does not return with -1 quickly enough, so when you re-enter the menu and select a new type of weapon/armour, it will proceed to use _that_ value for the old showMenu function call. A little complicated, but the idea is that we need to fix showMenu. By fixing showMenu we might also be able to fix the "busy" npcs when you click off talking to them and attempt to re-talk.
