### ISSUE TITLE
Opposing Player's in interfaces [v2.0.1 - BUG]

### ISSUE THREAD

**Issue by multi-talented** [Open-RSC/Game#687]
When you are trading with another player it should be just as fast in your screen as it is inside theirs. Both players should have the same latency.

It works OK in a Dueling interface.

**Comment by multi-talented** [comment]
I was using 2 accounts at the same time to see the delay.
Remember the other issue about the click and hold to increase gp in trades and banks? Same deal here, just should be real time changes between both players screens - have the same ticks.

**Comment by Christofosho** [comment]
Yup, I know - I know the error but it'll take a few to fix. It's gross code. :D

**Comment by multi-talented** [comment]
I have in person as it was back when real rsc was still online.
however the rsc+ replays don't  record user interactions in trade screen.

**Comment by Christofosho** [comment]
#795 sends to the server _before_ performing any GUI updates, to ensure the attempted trade is legal. This is slightly different than original RSC, because in RSC it would put the item in the GUI anyway - but the trade would end if the item was illegal so it didn't matter. I think this method ensures we don't get local trade issues involving wrong items in the GUI.
