### ISSUE TITLE
Launcher - Randomly Select Background Images That Don't Exist?

### ISSUE THREAD

**Issue by KeplerIO** [Open-RSC/Game#838]
**Describe the bug**
When the AppFrame builds, it generates random number 0-3 to decide which background image file to use. Getting passed that, you can see that background2.png and background3.png don't even exist in the current repo.
```
    public void build() {
    	Random rand = new Random();
        int value = rand.nextInt(3);
        if (value == 0) {
            (this.bg = new JLabel(Utils.getImage("background.png"))).setBounds(0, 0, 980, 560);
        }
        else if (value == 1) {
            (this.bg = new JLabel(Utils.getImage("background2.png"))).setBounds(0, 0, 980, 560);
        }
        else {
            (this.bg = new JLabel(Utils.getImage("background3.png"))).setBounds(0, 0, 980, 560);
        }
     }
```

**Screenshots**
![c6ee13143276375d9b0410e38d1e350c](https://user-images.githubusercontent.com/26471970/46590112-bf9c4f80-ca65-11e8-9bf7-b71babf2e78a.png)

**Desktop:**
 - OS: Windows 7 64-bit

**Comment by Marwolf** [comment]
![background](https://user-images.githubusercontent.com/16737510/46595952-bc768300-caa8-11e8-9664-42ac7b8c9569.png)
![background2](https://user-images.githubusercontent.com/16737510/46595953-bd0f1980-caa8-11e8-8718-7fd8d336c19f.png)
![background3](https://user-images.githubusercontent.com/16737510/46595954-bd0f1980-caa8-11e8-8a95-8a0ed86e18e0.png)

Not sure why they aren't in the repo. Haven't found root cause yet.

**Comment by KeplerIO** [comment]
Thank you sir, I thought I was crazy!
